// PAPER CONTEXT
export const CLEAR_PAPERS = "CLEAR_PAPERS";
export const FILTER_PAPERS = "FILTER_PAPERS";
export const GRADE_PAPER = "GRADE_PAPER";
export const UPDATE_PAPER = "UPDATE_PAPER";
export const DELETE_PAPER = "DELETE_PAPER";
export const ADD_PAPER = "ADD_PAPER";
export const REVIEW_PAPER = "REVIEW_PAPER";
export const BID_PAPER = "BID_PAPER";
export const GET_PAPERS = "GET_PAPERS";
export const PAPER_ERROR = "PAPER_ERROR";
export const CLEAR_FILTER_PAPERS = "CLEAR_FILTER_PAPERS";
// CONFERENCE CONTEXT
export const ADD_CONFERENCE = "ADD_CONFERENCE";
export const DELETE_CONFERENCE = "DELETE_CONFERENCE";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_CONFERENCE = "UPDATE_CONFERENCE";
export const FILTER_CONFERENCES = "FILTER_CONFERENCES";
export const CLEAR_FILTER_CONFERENCES = "CLEAR_FILTER_CONFERENCES";
export const CLEAR_CONFERENCES = "CLEAR_CONFERENCES";
export const CONFERENCE_ERROR = "CONFERENCE_ERROR";
export const GET_CONFERENCES = "GET_CONFERENCES";
export const GET_SECTIONS= "GET_SECTIONS";
export const ADD_SECTION= "ADD_SECTION";
export const SET_CURRENT_SECTION= "SET_CURRENT_SECTION";
export const CLEAR_CURRENT_SECTION= "CLEAR_CURRENT_SECTION";
//
export const ADD_PCMEMBER = "ADD_PCMEMBER"
export const ADD_LISTENER = "ADD_LISTENER"
export const ADD_AUTHOR = "ADD_AUTHOR"
// ALERT CONTEXT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// LOGIN CONTEXT
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const PERMISIONS_LOADED = "PERMISIONS_LOADED"
export const GLOBAL_PERMISSIONS_LOADED = "GLOBAL_PERMISSIONS_LOADED"
export const GETALL_USERS = "GETALL_USERS"